### PR TITLE
Serial port preparation

### PR DESCRIPTION
**Pull request by martinhoefling**
In case that port is not set to 115200 baud.

### CODE REVIEW

**Comment by jckuester** [comment]
Can you rebase this PR please?

**Comment by martinhoefling** [comment]
@jckuester it's up to date with your master after merging #16

**Comment by christiangroth** [comment]
Any chance that this PR and #18 will get merged soon and a new release will be published?

**Comment by martinhoefling** [comment]
@jckuester any chance to get it merged?

**Comment by jckuester** [comment]
@martinhoefling sorry for neglecting your PR.

**Pull request merged**
